#
# Copyright (C) 2017 Dremio Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# #baseDEP all offline, >1.2GB 1h
# FROM maven:3-jdk-8 as basedep
# WORKDIR /dremio
# RUN git clone -b multitenancy https://github.com/smartcommunitylab/dremio-oss.git
# WORKDIR /dremio/dremio-oss
# RUN mvn -Dmaven.repo.local=/dremio/m2 -Dmaven.artifact.threads=100 dependency:go-offline

# time real    2m2,517s

#baseDEP min cache 20M <1m
FROM maven:3.6-jdk-8 as basedep
WORKDIR /dremio
# RUN git clone -b multitenancy https://github.com/smartcommunitylab/dremio-oss.git
COPY . /dremio/dremio-oss
WORKDIR /dremio/dremio-oss
RUN  mkdir -p /root/.m2/repository/org/pentaho/pentaho-aggdesigner-algorithm/5.1.5-jhyde && curl https://public.nexus.pentaho.org/repository/proxy-public-3rd-party-release/org/pentaho/pentaho-aggdesigner-algorithm/5.1.5-jhyde/pentaho-aggdesigner-algorithm-5.1.5-jhyde.jar -o /root/.m2/repository/org/pentaho/pentaho-aggdesigner-algorithm/5.1.5-jhyde/pentaho-aggdesigner-algorithm-5.1.5-jhyde.jar && curl https://public.nexus.pentaho.org/repository/proxy-public-3rd-party-release/org/pentaho/pentaho-aggdesigner-algorithm/5.1.5-jhyde/pentaho-aggdesigner-algorithm-5.1.5-jhyde.pom -o /root/.m2/repository/org/pentaho/pentaho-aggdesigner-algorithm/5.1.5-jhyde/pentaho-aggdesigner-algorithm-5.1.5-jhyde.pom
RUN  mvn -T 1C install -DskipTests=true -Dlicense.skip -pl :dremio-common -am
RUN  mvn -T 1C install -DskipTests=true -Dlicense.skip -pl :dremio-services-users
RUN  mvn -T 1C package -DskipTests=true -Dlicense.skip -pl :dremio-sabot-logical
RUN  mvn -T 1C install -Dmaven.test.skip=true -Dlicense.skip -pl :dremio-dac-backend
RUN  mvn -T 1C install -DskipTests=true -Dlicense.skip -pl :dremio-dac-ui
RUN  mvn -T 1C package -Dmaven.test.skip=true -Dlicense.skip -DskipTests=true -pl :dremio-distribution -am
RUN mkdir -p /opt/dremio && mv /dremio/dremio-oss/distribution/server/target/dremio*.tar.gz /opt/dremio/dremio.tar.gz
RUN tar vxfz /opt/dremio/dremio.tar.gz -C /opt/dremio --strip-components=1 && rm /opt/dremio/dremio.tar.gz

FROM scratch
COPY --from=basedep /root/.m2 /root/.m2
