#
# Copyright (C) 2017 Dremio Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# #baseDEP all offline, >1.2GB 1h
# FROM maven:3-jdk-8 as basedep
# WORKDIR /dremio
# RUN git clone -b multitenancy https://github.com/smartcommunitylab/dremio-oss.git
# WORKDIR /dremio/dremio-oss
# RUN mvn -Dmaven.repo.local=/dremio/m2 -Dmaven.artifact.threads=100 dependency:go-offline

# time real    2m2,517s

#baseDEP min cache 20M <1m
FROM maven:3-jdk-8 as basedep
WORKDIR /dremio
# RUN git clone -b multitenancy https://github.com/smartcommunitylab/dremio-oss.git
COPY . /dremio/dremio-oss
WORKDIR /dremio/dremio-oss
RUN mvn -Dmaven.artifact.threads=100 clean
RUN mvn -T 1C install -DskipTests=true -Dlicense.skip -pl :dremio-common -am
RUN mvn -T 1C package -DskipTests=true -Dlicense.skip -pl :dremio-sabot-logical
RUN mvn -T 1C  package -Dmaven.test.skip=true -Dlicense.skip -pl :dremio-dac-backend
RUN mvn -T 1C  package -Dmaven.test.skip=true -Dlicense.skip -pl :dremio-distribution -am

FROM scratch
COPY --from=basedep /root/.m2 /root/.m2
